### ISSUE TITLE
Problème avec disqus

### ISSUE THREAD

**Issue by GuyliannEngels** [ShawnLemaire/shawn-shawn_blog#1]
Salut @ShawnLemaire,

Je n'ai aps accès à ton travail comme tu le sais. Tu as appris dans le module 3  ce que c'etait que d'être un collaborateur. 

J'ai donc un peu regardé à ton projet afin de t'aider à trouver ton erreur avec disqus. Ma première piste serait de remplacer `hiden` par `hidden`

```
collections:
  posts:
    disqus: 
      shortname: reproducible-finance-with-r
      hidden: false
    share: [twitter, linkedin]          
``` 

As tu tenté cette solution là aussi non ? 

```
collections:
  posts:
    disqus: reproducible-finance-with-r
    share: [twitter, linkedin]
```

_Ceci est une issue. Tu as appris des notions théoriques sur ce que c'est. Lorsque notre échanges sur ton problème sur disqus sera terminé, n'oublie pas de fermer cette issue_
